articles: Artigos
categories: Categorias
search: Procurar
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: Ante
next: Próx
comment: Comentários
archive_a: Arquivos
archive_b: "Arquivos: %s"
page: Página %d
recent_posts: Publicações Recentes
newer: Recente
older: Antigo
share: Partilhar
powered_by: Powered by
rss_feed: RSS Feed
category: Categoria
tag: Tag
nav.category: Categoria
nav.tag: Tag
nav.archive: Arquivo
time_suffix: mins.
load_more: Carregar mais
toc: Conteúdo
read_article: Ler artigo
pv: Visualizações de Página
uv: Visitantes únicos
readed: Lido
word_count: Contagem de palavras
read_time: Tempo de leitura
read_count: Número de leituras
default_category: Artigo
search_initialise: A iniciar indice de procura...
search_start: Por favor introduza a procura.
search_empty: Sem resultados, por favor tente outra procura.
